version: '3'
services:
  proxy_redis:
    image: 'redis:alpine'
    container_name: proxy_redis
    command: redis-server --requirepass proxypool
    ports:
     - "4969:6379"
  proxy_server:
    build: .
    image: 'my_proxypool'
    container_name: proxy_server
    ports:
     - "5000:5000"
     - "80:80"
    restart: always
    environment:
     #REDIS_HOST: 'redis://@proxy_redis:6379/0'
     REDIS_HOST: proxy_redis